### ISSUE TITLE
I hope to add a suggestion that you can drink fruit juice

### ISSUE THREAD

**Issue by 1450143535** [Shlygly/LethalCompanyJuicesMod#7]
Thank you very much for creating this juice mod. I really like it, but I would like to make a suggestion. Can we update it in the future to add a feature to the juice that allows players to interact with it, such as drinking juice? This will make the mod more fun

**Comment by Shlygly** [comment]
Glad you like the mod !
At the moment I'm not actively working on it, but I was already planning to add new features some day. Having bonuses and/or penalties when you drink a juice is a good idea (maybe only certain juice formats), I'll think about it.

**Comment by Shlygly** [comment]
I've added the juice-drinking feature for cans only.
Drinking a can will trigger some juice effects (see readme).

Details in 423ded3
